### ISSUE TITLE
Have a standalone titlepage to use on book class

### ISSUE THREAD

**Issue by martinrgt** [SCD-Aix-Marseille-Universite/latexamu#32]
Hello, 
I am writing my thesis at AMU but I used the book class. When I tried to integrate the official titlepage I saw that it used some unknown packages. Is there any way to get a standalone titlepage in order to input it to my document?
Thank you, 
Martin

**Comment by eurruby** [comment]
Hi,

Done : https://github.com/SCD-Aix-Marseille-Universite/latexamu-intro
