### ISSUE TITLE
Cannot compile these.tex, too many issues. :-)

### ISSUE THREAD

**Issue by karumbis** [SCD-Aix-Marseille-Universite/latexamu#34]
Hello.

We want to use the latest sty files from the AMU for a thesis.

We tried to compile the `these.tex` file as described in the `readme.md` file. We work under Lubuntu 18.04 and pre-installed a working Tex Live environment (pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)). We additionally installed:

```
sudo apt-get install texlive-lang-french
sudo apt-get install texlive-fonts-extra
sudo apt-get install texlive-science
```

So, during the compilation, latex cannot find some figures. We de-activated them so far by un-commenting. However, then there is a problem with the `amu_these.cls`. We obtain the error:

```
! Undefined control sequence.
\ifstr ->\Ifstr
```

We then uncommented the following line in `amu_these.cls`:

`%\renewcommand{\ifstr}{\Ifstr} `

We then obtain the error:

```
! Undefined control sequence.
\iftocfeature ->\Iftocfeature
```

We therefore uncommented the next line in `amu_these.cls`:

`%\renewcommand{\iftocfeature}{\Iftocfeature}`

However, we then obtained a couple of other warnings and errors:

```
LaTeX Font Warning: Some font shapes were not available, defaults substituted.

 )
(see the transcript file for additional information)pdfTeX warning (dest): name
{glo:alpha} has been referenced but does not exist, replaced by a fixed one

pdfTeX warning (dest): name{glo:aa} has been referenced but does not exist, rep
laced by a fixed one

pdfTeX warning (dest): name{glo:Aa} has been referenced but does not exist, rep
laced by a fixed one

pdfTeX warning (dest): name{glo:ca} has been referenced but does not exist, rep
laced by a fixed one

pdfTeX warning (dest): name{glo:2a} has been referenced but does not exist, rep
laced by a fixed one

pdfTeX warning (dest): name{glo:+a} has been referenced but does not exist, rep
laced by a fixed one

pdfTeX warning (dest): name{glo:rutile} has been referenced but does not exist,
 replaced by a fixed one

pdfTeX warning (dest): name{glo:asb} has been referenced but does not exist, re
placed by a fixed one

{/usr/share/texmf/fonts/enc/dvips/lm/lm-ec.enc}{/usr/share/texlive/texmf-dist/f
onts/enc/dvips/base/8r.enc}{/usr/share/texmf/fonts/enc/dvips/cm-super/cm-super-
ts1.enc}
!pdfTeX error: pdflatex (file T1-WGL4.enc): cannot open encoding file for readi
ng
 ==> Fatal error occurred, no output PDF file produced!
```

... obviously, some fonts cannot be found by LaTeX and so on ... .

What can we do? Please, can you check the entire thing and supply also the missing figures?

Thanks a lot in advance.

**Comment by eurruby** [comment]
As you can see here, there are no errors at compile time. Nor any warnings :
https://www.overleaf.com/read/krvhynbdwfdh

Please keep in mind that this is a complete example so all files are required. But of course this can be adapted to your use case.

**Comment by vpicouet** [comment]
You need to comment those 2 lines in amu_these.cls:
```
%\renewcommand{\ifstr}{\Ifstr}               %% supprime les 'warnings' des packages non mis à jour
%\renewcommand{\iftocfeature}{\Iftocfeature} %% selon les recommendations de The LaTeX Project Team
```
