### ISSUE TITLE
Font packages and selection

### ISSUE THREAD

**Issue by mlincett** [SCD-Aix-Marseille-Universite/latexamu#36]
In the class file `amu_these.cls` the `\RequirePackage{fourier}` is described as `%% fusion des lignes dans les tableaux` but it actually replaces the whole document typesetting, using Adobe Utopia fonts.

Also does `fourier` totally replace `lmodern`? If so, it is confusing to keep both. Maybe the command can be moved right after the inclusion `lmodern` or state that one has to choose between the two.

Using `fourier`, it is not also very clear the use case for  `%\renewcommand*{\rmdefault}{bch}` since the Charter typeface is not so different much different. It would be useful if one was using `lmodern` by default, no?

If @eurruby can give a look maybe we can think of doing some cleanup and harmonisation.

**Comment by eurruby** [comment]
Thank you very much for pointing out this inconsistency. I have modified the class according to your recommendations.

[fonts consistency](https://github.com/SCD-Aix-Marseille-Universite/latexamu/commit/49171d5be909b61a6a4e51a464f003d1d29c3094)

**Comment by mlincett** [comment]
Thanks for your follow up of this @eurruby !

May I suggest Latin Modern Sans Serif (`lmss`) for the titles instead of Helvetica (`qhv`)? Helvetica ends up lookig pretty heavy, while I think `lmss` blends in better with Utopia fonts.
