### ISSUE TITLE
Glossary not appearing (Persistent issue)

### ISSUE THREAD

**Issue by reyhashemi** [SCD-Aix-Marseille-Universite/latexamu#50]
Hi !

I uploaded the template project to overleaf and wrote my whole thesis there. When I compile my thesis. The the glossary files are not printed in the beginning of the thesis, neither in the TOC nor after the LOT. 

I initially thought that it might be due to a package conflict and my modified .cls file. But even using your own .cls and these.tex it did not work as expected. 

I finally found out that I do not have the .latexmkrc file in my project. so i added it manually but still no success.

I have to submit my thesis in few days and really need to solve this issue. Your help is highly appreciated.

Thank you.

**Comment by eurruby** [comment]
you need to compile on your workstation to be sure it works
sorry for the delay in replying
