### ISSUE TITLE
Compilation timeout

### ISSUE THREAD

**Issue by pinpss** [SCD-Aix-Marseille-Universite/latexamu#51]
_"Your compile timed out
This project exceeded the compile timeout limit on our free plan.

Tell the project owner and ask them to upgrade their Overleaf plan if you need more compile time.
Reasons for compile timeouts
We’ve recently [reduced the compile timeout limit](https://www.overleaf.com/blog/changes-to-free-compile-timeouts-and-servers) on our free plan, which may have affected this project.

Common causes of compile timeouts include:

Large or high-resolution images taking too long to process. You may be able to [optimize them](https://www.overleaf.com/learn/how-to/Optimising_very_large_image_files).
A [fatal compile error](https://www.overleaf.com/learn/how-to/Fixing_and_preventing_compile_timeouts#Step_3:_Assess_your_project_for_time-consuming_tasks_and_fatal_errors) that completely blocks the compilation. Enable  under the Recompile drop-down menu to help you find and fix errors right away.
[Learn more](https://www.overleaf.com/learn/how-to/Fixing_and_preventing_compile_timeouts) about other causes of compile timeouts and how to fix the..."_

**Comment by eurruby** [comment]
Overleaf ne permet plus de compiler le modèle depuis la mise à jour des limites de temps de compilation avec le plan gratuit. Le lien vers Overleaf a donc été supprimé.
