### ISSUE TITLE
Multiple error

### ISSUE THREAD

**Issue by kenzamroune** [SCD-Aix-Marseille-Universite/latexamu#52]
Bonjour, j'ai la même erreur dans les différentes sections du document :

Class scrreprt Error: undefined old font command `\rm'.

**Comment by kenzamroune** [comment]
Pour info, j'utilise overleaf.

**Comment by kenzamroune** [comment]
Voici le message d'erreur:

See the scrreprt class documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1 \chapter{Introduction}
                          
You should note that since 1994 LaTeX2e provides a new font selection scheme
called NFSS2 with several new, combinable font commands. KOMA-Script
classes had defined the old font commands like `\rm' only for compatibility
with old LaTeX 2.09 document styles of Script 2.0. Nevertheless, these
commands are deprecated and undocumented at least since 2003. Since 2013
KOMA-Script classes warned about soon removement of these deprecated commands.
Now, after two decades of LaTeX2e and NFSS2, these commands will not work any
more. If loading a package results in this error message, you should contact
the author of that package and ask him to replace the deprecated font command
`\rm', e.g., by `\normalfont \rmfamily `. Otherwise you should reconfigure
or replace the package. If you have used the old font command `\rm' yourself,
you should replace it, e.g., by `\normalfont \rmfamily '.
To make it work for now, you can use the already also deprecated class option
`enabledeprecatedfontcommands'.

**Comment by eurruby** [comment]
Bonjour,
Normalement cette erreur ne doit plus apparaître depuis la mise à jour du modèle intégrant la nouvelle charte graphique AMU.
